apiVersion: v1
kind: PersistentVolume

metadata:
  name: mongo-pv-a

spec:
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Recycle

  gcePersistentDisk:
    pdName: mongo-pd
    fsType: ext4
